server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dingjianhui1013/springcloud-config.git #GitHub上面的git仓库名字
          default-label: main
          clone-on-start: true
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka, http://www.eureka7002.com:7002/eureka
