server:
  port: 7001
eureka:
  instance:
#    单机版本
#    hostname: localhost #eureka服务端的实例名字
  #集群版本
    hostname: www.eureka7001.com #eureka服务端的实例名字
  client:
    #表识不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      单机版本
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      集群版本
      defaultZone: http://www.eureka7002.com:7002/eureka/ # 如果是两台以上的话则，指向除自己以外的所有服务中心地址并用逗号分割并用逗号分割，defaultZone: http://www.eureka7002.com:7002/eureka/,http://www.eureka7003.com:7003/eureka/
